import 'cypress-xpath';

export const customerInformationPageLocators = {
    firstStepperName: `//span[@data-element-name="booking-page-stepper-1"]`,
    pageTitle: `//h3[text()='Contact details']`,
    initialPrice: `(//div[@data-component="mob-flight-price-breakdown-wrapper"]/descendant::span[@data-component="mob-price-desc-text"])[1]`,
    baseFare: `(//div[@data-component="mob-flight-price-breakdown-wrapper"]/descendant::span[@data-component="mob-price-desc-text"])[2]`,
    taxesAndFees: `(//div[@data-component="mob-flight-price-breakdown-wrapper"]/descendant::span[@data-component="mob-price-desc-text"])[3]`,
    discountAmount:`(//div[@data-component="mob-flight-price-breakdown-wrapper"]/descendant::span[@data-component="mob-price-desc-text"])[4]`,
    totalPrice: `(//div[@data-component="mob-flight-price-breakdown-wrapper"]/descendant::span[@data-component="mob-price-desc-text"])[7]`,
    firstNameInput: `//input[@id="contact.contactFirstName"]`,
    lastNameInput: `//input[@id="contact.contactLastName"]`,
    emailInput: `//input[@id="contact.contactEmail"]`,
    countryOfResidenceDropdown: `//div[@data-testid="contact.contactCountryOfResidenceId"]/descendant::p`,
    searchCountryInput: `(//div[@data-testid="floater-container"]/descendant::input)[1]`,
    firstCountryOption: `(//div[@data-testid="floater-container"]/descendant::input)[2]`,
    phoneNumberCountryCodeDropdown: `//div[@data-testid="contact.contactPhoneNumber-CountryCodeDataTestId"]/descendant::p`,
    phoneNumberInput: `//input[@id="contact.contactPhoneNumber"]`,
    genderFemaleOption: `//p[text()='Female']`,
    genderMaleOption: `//p[text()='Male']`,
    passengerFirstandMiddleNameInput: `//input[@id="flight.forms.i0.units.i0.passengerFirstName"]`,
    passengerLastNameInput: `//input[@id="flight.forms.i0.units.i0.passengerLastName"]`,
    passengerDayOfBirthInput: `//input[@datatestid="flight.forms.i0.units.i0.passengerDateOfBirth-DateInputDataTestId"]`,
    passengerMonthOfBirthDropdown: `//div[@data-testid="flight.forms.i0.units.i0.passengerDateOfBirth-MonthInputDataTestId"]/descendant::p`,
    firstMonthOption: `(//div[@data-testid="floater-container"]/descendant::span)[1]`,
    passengerYearOfBirthInput: `//input[@datatestid="flight.forms.i0.units.i0.passengerDateOfBirth-YearInputDataTestId"]`,
    passengerNationalityDropdown: `//div[@data-testid="flight.forms.i0.units.i0.passengerNationality"]/descendant::p`,
    passportNumberInput: `//input[@id="flight.forms.i0.units.i0.passportNumber"]`,
    countryOfIssueDropdown: `//div[@data-testid="flight.forms.i0.units.i0.passportCountryOfIssue"]/descendant::p`,
    passportExpiryDateInput: `//input[@datatestid="flight.forms.i0.units.i0.passportExpiryDate-DateInputDataTestId"]`,
    passportExpiryMonthDropdown: `//div[@data-testid="flight.forms.i0.units.i0.passportExpiryDate-MonthInputDataTestId"]/descendant::p`,
    passportExpiryYearInput: `//input[@datatestid="flight.forms.i0.units.i0.passportExpiryDate-YearInputDataTestId"]`,
    travelProtectionNoOption: `//p[text()='No, thanks, I’ll risk it.']`,
    continueToPaymentButton: `//div[text()='Continue to payment']`,
    popUpConformationToUpgradeSupportLevel: `(//h3[text()='Upgrade your support level'])[2]`,
    popUpConformationToUpgradeSupportLevelNoThanksButton: `//button[@data-element-name="decline-button"]`
};